### ISSUE TITLE
Switching styles on amazon sometimes makes the button disappear.

### ISSUE THREAD

**Issue by dylanbathurst** [Purse/buywithbitcoin#6]

**Comment by dylanbathurst** [comment]
example product: https://www.amazon.com/Feelin-Good-Tees-Sarcastic-Graphic/dp/B01K0BZYBI/ref=pd_sim_193_4?_encoding=UTF8&pd_rd_i=B07CQYMC11&pd_rd_r=B0VMQ9TJX0H81MRM3W8E&pd_rd_w=7imBe&pd_rd_wg=bc9MB&refRID=B0VMQ9TJX0H81MRM3W8E&th=1&psc=1

**Comment by razorman8669** [comment]
no longer an issue. closing.
